$("#l-one").click(function(){
  $("#start").hide();
  $("#i-three").hide();
  $("#i-one").show();
  $("#i-two").hide();
  $("#i-four").hide();
  $("#i-five").hide();
  $("#i-six").hide();
});
$("#l-two").click(function(){
  $("#i-one").hide();
  $("#i-three").hide();
  $("#start").hide();
  $("#i-two").show();
  $("#i-four").hide();
  $("#i-five").hide();
  $("#i-six").hide();
});
$("#l-three").click(function(){
  $("#i-one").hide();
  $("#i-two").hide();
  $("#start").hide();
  $("#i-three").show();
  $("#i-four").hide();
  $("#i-five").hide();
  $("#i-six").hide();
});
$("#l-four").click(function(){
  $("#i-one").hide();
  $("#i-two").hide();
  $("#start").hide();
  $("#i-three").hide();
  $("#i-four").show();
  $("#i-five").hide();
  $("#i-six").hide();
});
$("#l-five").click(function(){
  $("#i-one").hide();
  $("#i-two").hide();
  $("#start").hide();
  $("#i-three").hide();
  $("#i-four").hide();
  $("#i-five").show();
  $("#i-six").hide();
});
$("#l-six").click(function(){
  $("#i-one").hide();
  $("#i-two").hide();
  $("#start").hide();
  $("#i-three").hide();
  $("#i-four").hide();
  $("#i-five").hide();
  $("#i-six").show();
});
